AWSTemplateFormatVersion: "2010-09-09"

Mappings:
  RegionMap:
    ap-northeast-1:
      ImageId: "ami-0b276ad63ba2d6009"
      HostedId: "Z1YSHQZHG15GKL"
      AZs: 'ap-northeast-1a,ap-northeast-1c'
    ap-northeast-2:
      ImageId: "ami-0b827f3319f7447c6"
      HostedId: "Z20JF4UZKIW1U8"
      AZs: 'ap-northeast-2a,ap-northeast-2b,ap-northeast-2c'
    ap-northeast-3:
      ImageId: "ami-0e787554e61105680"
      HostedId: "Z5LXEXXYW11ES"
      AZs: 'ap-northeast-3a,ap-northeast-3b,ap-northeast-3c'
    us-east-2:
      ImageId: "ami-0233c2d874b811deb"
      HostedId: "ZOJJZC49E0EPZ"
      AZs: 'us-east-2a,us-east-2b,us-east-2c'
    us-east-1:
      ImageId: "ami-0dc2d3e4c0f9ebd18"
      HostedId: "Z1UJRXOUMOOFQ8"
      AZs: 'us-east-1a,us-east-1b,us-east-1c'
    us-west-1:
      ImageId: "ami-0ed05376b59b90e46"
      HostedId: "Z2MUQ32089INYE"
      AZs: 'us-west-1b,us-west-1c'
    us-west-2:
      ImageId: "ami-0dc8f589abe99f538"
      HostedId: "Z2OJLYMUO9EFXC"
      AZs: 'us-west-2a,us-west-2b,us-west-2c'
    ap-south-1:
      ImageId: "ami-00bf4ae5a7909786c"
      HostedId: "Z3VO1THU9YC4UR"
      AZs: 'ap-south-1a,ap-south-1b,ap-south-1c'
    ap-southeast-1:
      ImageId: "ami-0e5182fad1edfaa68"
      HostedId: "ZL327KTPIQFUL"
      AZs: 'ap-southeast-1a,ap-southeast-1b,ap-southeast-1c'
    ap-southeast-2:
      ImageId: "ami-0c9fe0dec6325a30c"
      HostedId: "Z2RPCDW04V8134"
      AZs: 'ap-southeast-2a,ap-southeast-2b,ap-southeast-2c'
    ca-central-1:
      ImageId: "ami-0db72f413fc1ddb2a"
      HostedId: "Z19DQILCV0OWEC"
      AZs: 'ca-central-1a,ca-central-1b,ca-central-1d'
    eu-central-1:
      ImageId: "ami-00f22f6155d6d92c5"
      HostedId: "Z1U9ULNL0V5AJ3"
      AZs: 'eu-central-1a,eu-central-1b,eu-central-1c'
    eu-west-1:
      ImageId: "ami-058b1b7fe545997ae"
      HostedId: "ZLY8HYME6SFDD"
      AZs: 'eu-west-1a,eu-west-1b,eu-west-1c'
    eu-west-2:
      ImageId: "ami-03ac5a9b225e99b02"
      HostedId: "ZJ5UAJN8Y3Z2Q"
      AZs: 'eu-west-2a,eu-west-2b,eu-west-2c'
    eu-west-3:
      ImageId: "ami-062fdd189639d3e93"
      HostedId: "Z3KY65QIEKYHQQ"
      AZs: 'eu-west-3a,eu-west-3b,eu-west-3c'
    eu-north-1:
      ImageId: "ami-00517306b63c4628c"
      HostedId: "Z3UWIKFBOOGXPP"
      AZs: 'eu-north-1a,eu-north-1b,eu-north-1c'
    sa-east-1:
      ImageId: "ami-05e809fbeee38dd5e"
      HostedId: "ZCMLWB8V5SYIT"
      AZs: 'sa-east-1a,sa-east-1b,sa-east-1c'
    # ap-east-1:
    #   HostedId: "Z3FD1VL90ND7K5"
    #   AZs: 'ap-east-1a,ap-east-1b,ap-east-1c'
    # me-south-1:
    #   HostedId: "Z20ZBPC0SS8806"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: Required parameters
        Parameters:
          - AllowIP
          - BucketName
          - BucketPrefix
          - BucketRegion
          - SSMAccess
          - DeployHTTPS
          - DeployC1NS
          - DeployC1NSHA
          - DeploySplunk
      - 
        Label:
          default: If you set the DeployHTTPS parameter to true, the following parameters are required
        Parameters:
          - DomainName
          - SubDomain
          - HostZoneID
      - 
        Label:
          default: If you set the DeployC1NS parameter to true, the following parameters are required
        Parameters:
          - sshKeyPairName
          - CloudOneAPIKEY
          - NSVAAMI
          - InstanceType
          - SecurityVPCCIDR
          - NsvaCountPerAz
          - EnableInspectionLogs
      - 
        Label:
          default: If you set the DeploySplunk parameter to true, the following parameters are required
        Parameters:
          - SyslogPort
          - SplunkPassword
          - SplunkVersion

Parameters:
  # ------------------------------------------------------------#
  # Required parameters
  # ------------------------------------------------------------#
  AllowIP:
    Description: Enter the global IP of the terminal to be tested.
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "Must be a valid IP range of the form x.x.x.x/x"
    Default: '72.48.66.44/32'
  BucketName:
    Description: Name of the bucket where the template is placed
    Type: String
    Default: 'quickstart-ns-edge-deployment'
  BucketPrefix:
    Description: bucket prefix
    Type: String
    Default: 'centralized-with-gwlb/'
  BucketRegion:
    Description: bucket region
    Type: String
    Default: 'us-west-1'
  SSMAccess:
    Description: If enabled, SSM access to the instance will be available.
    Type: String
    AllowedValues: [true, false]
    Default: true
  DeployHTTPS:
    Description: If enabled, The HTTPS site will be deployed.
    Type: String
    AllowedValues: [true, false]
    Default: false
  DeployC1NS:
    Description: If enabled, C1NS deployed option 2 
    Type: String
    AllowedValues: [true, false]
    Default: true
  DeployC1NSHA:
    Description: "[Required 'DeployC1NS' must be set to true] If enabled, C1NS HA deployed."
    Type: String
    AllowedValues: [true, false]
    Default: false
  DeploySplunk:
    Description: "[Required 'DeployC1NS' must be set to true] If enabled, Splunk Server will be deployed."
    Type: String
    AllowedValues: [true, false]
    Default: false
  # ------------------------------------------------------------#
  # If you set the DeployHTTPS parameter to true, the following parameters are required
  # ------------------------------------------------------------#
  DomainName:
    Description: Enter the domain name to be used for the website.
    Type: String
    Default: 'anonymass-nemo.uk'
  SubDomain:
    Description: Enter the subdomain to be used for the ALB.
    Type: String
    Default: ''
  HostZoneID:
    Description: Enter the ID of the HostZone where the domain you want to use is registered.
    Type: String
    Default: 'Z085817336XNWEPQIO5DS'
  # ------------------------------------------------------------#
  # If you set the DeployC1NS parameter to true, the following parameters are required
  # ------------------------------------------------------------#
  sshKeyPairName:
    Description: Select the SSHKey of the EC2 you are using.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  CloudOneAPIKEY:
    Description: Enter the CloudOne API key you want to use.
    Type: String
    NoEcho: true
    Default: "2B63DC27-2498-AADC-B5B4-63CB3FFE880E:134B7928-9F25-63E4-B0A9-B9D0853DB8F9:pZmiQS5nWtOtcUhdSC0DKABDP89WWLDpZqu5WNKGkKM="
  NSVAAMI:
    Description: Enter the AMIID of the NSVA to be deployed
    Type: AWS::EC2::Image::Id
    Default: "ami-0346f9bbf24feece4"
  InstanceType:
    Description: Select the instance type of NSVA
    Type: String
    AllowedValues:
      - c5.9xlarge
      - c5.4xlarge
      - c5.2xlarge
      - c5n.9xlarge
      - c5n.4xlarge
      - c5n.2xlarge
    Default: c5n.2xlarge
  SecurityVPCCIDR:
    Description: Specify the CIDR of the VPC where you want to deploy the NSVA.
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-6]))$"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/16-26"
    Default: "10.10.10.0/16"
  NsvaCountPerAz:
    Description: Select the number of NSVA instances to be deployed in the AZ.
    Type: Number
    AllowedValues:
      - 1
      - 2
      - 3
      - 4
    Default: 1
  EnableInspectionLogs:
    Description: If enabled, NSVA Inspection Logs will be published to CloudWatch log group "network_security_logs".
    Type: String
    AllowedValues: [ true, false ]
    Default: false
  # ------------------------------------------------------------#
  # If you set the DeploySplunk parameter to true, the following parameters are required
  # ------------------------------------------------------------#
  SyslogPort:
    Description: Port number used by Splunk Server
    Type: String
    Default: '5140'
  SplunkPassword:
    Description: Password used by Splunk Server
    Type: String
    NoEcho: true
    Default: 'Trendmicr0!'
  SplunkVersion:
    Description: Splunk Version
    Type: String
    Default: '8.2'

# ------------------------------------------------------------#
# Conditions
# ------------------------------------------------------------#
Conditions:
  DeployHTTPS:
    !Equals [true, !Ref DeployHTTPS]
  DeployC1NS:
    !Equals [true, !Ref DeployC1NS]
  DeployC1NSHAmodel:
    !Equals [true, !Ref DeployC1NSHA]
  DeployC1NSHA: !And
    - !Condition DeployC1NS
    - !Condition DeployC1NSHAmodel
  DeploySplunksrv:
    !Equals [true, !Ref DeploySplunk]
  DeploySplunk: !And
    - !Condition DeployC1NS
    - !Condition DeploySplunksrv

Resources:
  # ------------------------------------------------------------#
  # Create Base VPC (VPC, IGW, Subnet, RouteTable, EIP, NatGW)
  # ------------------------------------------------------------#
  BaseVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${BucketRegion}.amazonaws.com/${BucketPrefix}aws-vpc.template.yaml
      Parameters:
        NumberOfAZs: 2
        AvailabilityZones: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - AZs

  # ------------------------------------------------------------#
  # Create Base Site (EC2, SecurityGroup)
  # ------------------------------------------------------------#
  BaseSite:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${BucketRegion}.amazonaws.com/${BucketPrefix}BaseSite.yaml
      Parameters:
        ImageId: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - ImageId
        AllowIP: !Ref AllowIP
        NeedSSMAccess: !Ref SSMAccess
        VPCId: !GetAtt BaseVPC.Outputs.VPCID
        PrivateSubnet1ID: !GetAtt BaseVPC.Outputs.PrivateSubnet1AID
        PublicSubnet1ID: !GetAtt BaseVPC.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt BaseVPC.Outputs.PublicSubnet2ID

  # ------------------------------------------------------------#
  # Create LoadBalancer and https site (ALB, TargetGroup, Listener, ACM)
  # ------------------------------------------------------------#
  AddALB:
    Condition: DeployHTTPS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${BucketRegion}.amazonaws.com/${BucketPrefix}AddALB.yaml
      Parameters:
        DomainName: !Ref DomainName
        SubDomain: !Ref SubDomain
        HostZoneID: !Ref HostZoneID
        TargetGroupID: !GetAtt BaseSite.Outputs.TargetGroupID
        ALBID: !GetAtt BaseSite.Outputs.ALBID
        HostedZoneId: !GetAtt BaseSite.Outputs.HostedZoneId
        DNSName: !GetAtt BaseSite.Outputs.HTTPWebSiteURL

  # ------------------------------------------------------------#
  # Create RemoveRecord Function
  # ------------------------------------------------------------#
  RemoveRecord:
    Condition: DeployHTTPS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${BucketRegion}.amazonaws.com/${BucketPrefix}RemoveRecord.yaml
      Parameters:
        HostZoneID: !Ref HostZoneID

  # ------------------------------------------------------------#
  # Create c1ns macro template
  # ------------------------------------------------------------#
  c1nsMacroTemaplte:
    Condition: DeployC1NS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://trendmicro-tippingpoint.s3.amazonaws.com/documentation/templates/macro.yml

  # ------------------------------------------------------------#
  # Create c1ns security vpc template
  # ------------------------------------------------------------#
  c1nsSecurityVPCTemaplte:
    Condition: DeployC1NS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://trendmicro-tippingpoint.s3.amazonaws.com/documentation/templates/security_vpc.yml
      Parameters:
        sshKeyPairName: !Ref sshKeyPairName
        CloudOneAPIKEY: !Ref CloudOneAPIKEY
        NSVAAMI: !Ref NSVAAMI
        InstanceType: !Ref InstanceType
        AvailabilityZones: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - AZs
        SecurityVPCCIDR: !Ref SecurityVPCCIDR
        NsvaCountPerAz: !Ref NsvaCountPerAz
        EnableInspectionLogs: !Ref EnableInspectionLogs
    DependsOn: c1nsMacroTemaplte

  # ------------------------------------------------------------#
  # Create the IAM role stack for cross-account deployments 
  # ------------------------------------------------------------#
  CrossAccountIAMTemplate:
    Condition: DeployC1NSHA
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://trendmicro-tippingpoint.s3.amazonaws.com/documentation/templates/ha_lambda_cross_account_iam.yaml
      Parameters:
        SecurityVpcAccountId: !Ref "AWS::AccountId"
        ExternalId: !GetAtt c1nsSecurityVPCTemaplte.Outputs.ExternalId
    DependsOn: ModifyRTTemplate

  # ------------------------------------------------------------#
  # Create HA stack deployments
  # ------------------------------------------------------------#
  HaLambdaTemplate:
    Condition: DeployC1NSHA
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://trendmicro-tippingpoint.s3.amazonaws.com/documentation/templates/ha_resources_vpc_ingress.yaml
      Parameters:
        securityVpcStackName: 
          Fn::Select:
            - 1
            - Fn::Split:
              - /
              - !Ref c1nsSecurityVPCTemaplte
    DependsOn: CrossAccountIAMTemplate

  # ------------------------------------------------------------#
  # Create Last modify setting template (modify route table)
  # ------------------------------------------------------------#
  ModifyRTTemplate:
    Condition: DeployC1NS
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${BucketRegion}.amazonaws.com/${BucketPrefix}last.yaml
      Parameters:
        VPC: !GetAtt BaseVPC.Outputs.VPCID
        InternetGateway: !GetAtt BaseVPC.Outputs.IGWID
        BasePublicSubnet1CIDR: !GetAtt BaseVPC.Outputs.PublicSubnet1CIDR
        BasePublicSubnet2CIDR: !GetAtt BaseVPC.Outputs.PublicSubnet2CIDR
        BasePublicSubnet1RouteTable: !GetAtt BaseVPC.Outputs.PublicSubnet1RouteTable
        BasePublicSubnet2RouteTable: !GetAtt BaseVPC.Outputs.PublicSubnet2RouteTable
        VPCEndpointServiceName: !GetAtt c1nsSecurityVPCTemaplte.Outputs.VPCEndpointServiceName
        AvailabilityZones: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - AZs

  # ------------------------------------------------------------#
  # Create Splunk Server
  # ------------------------------------------------------------#
  SplunkTemplate:
    Condition: DeploySplunk
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.${BucketRegion}.amazonaws.com/${BucketPrefix}splunk.yaml
      Parameters:
        VPCID: !GetAtt BaseVPC.Outputs.VPCID
        VPCCIDR: !GetAtt BaseVPC.Outputs.VPCCIDR
        RTID: !GetAtt ModifyRTTemplate.Outputs.PublicSubnet1Route
        AllowIP: !Ref AllowIP
        SyslogPort: !Ref SyslogPort
        SecurityVPCCIDR: !Ref SecurityVPCCIDR
        ImageId: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - ImageId
        PublicSubnet1ID: !GetAtt ModifyRTTemplate.Outputs.PublicSubnet1ID
        SplunkPassword: !Ref SplunkPassword
        SplunkVersion: !Ref SplunkVersion
        c1nsStackName: 
          Fn::Select:
            - 1
            - Fn::Split:
              - /
              - !Ref c1nsSecurityVPCTemaplte
        InstanceProfile: !GetAtt BaseSite.Outputs.InstanceProfile
        NeedSSMAccess: !Ref SSMAccess

# ------------------------------------------------------------#
# Output Site URLs
# ------------------------------------------------------------#
Outputs:
  HTTPWebSiteURL:
    Value: !GetAtt BaseSite.Outputs.HTTPWebSiteURL
    Description: HTTP site URL
  HTTPSWebSiteURL:
    Condition: DeployHTTPS
    Value: !GetAtt AddALB.Outputs.HTTPSWebSiteURL
    Description: HTTPS site URL
  SplunkURL:
    Condition: DeploySplunk
    Value: !GetAtt SplunkTemplate.Outputs.SplunkURL
    Description: Splunk URL
  SplunkInternalIP:
    Condition: DeploySplunk
    Value: !GetAtt SplunkTemplate.Outputs.SplunkInternalIP
    Description: Splunk private IP address  