AWSTemplateFormatVersion: 2010-09-09

Parameters:
  # ------------------------------------------------------------#
  # Import Master.yaml template
  # ------------------------------------------------------------#
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Select the AZ to deploy GWLB Endpoint. Note:
      The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  GWLBEndpointSubnet1CIDR:
    Description: Enter the GWLB Subnet CIDR to deploy the GWLBE, CIDR block for the GWLB DMZ subnet 1 located in Availability Zone
      1
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.201.0/24
  GWLBEndpointSubnet2CIDR:
    Description: Enter the GWLB Subnet CIDR to deploy the GWLBE, CIDR block for the GWLB DMZ subnet 2 located in Availability Zone
      2
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.202.0/24
  TGWAttachmentSubnet1CIDR:
    Description: Enter the TGW Attachement Subnet CIDR
      1
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.211.0/24
  TGWAttachmentSubnet2CIDR:
    Description:  Enter the TGW Attachement Subnet CIDR
      2
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.212.0/24
  # ------------------------------------------------------------#
  # Import c1nsSecurityVPCTemplate stack(security_vpc.yml file)
  # ------------------------------------------------------------#
  VPC:
    Description: Enter the VPC ID where you want to deploy the GWLB Endpoint
    Type: String
  VPCEndpointServiceName:
    Description: VPC Endpoint Service Name
    Type: String

Resources:
  # ------------------------------------------------------------#
  # Create GWLB Subnet for GWLB Endpoint
  # ------------------------------------------------------------#
  GWLBEndpointSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref GWLBEndpointSubnet1CIDR
      AvailabilityZone: !Select
        - 0
        - !Ref AvailabilityZones
      Tags:
        - Key: Name
          Value: GWLB subnet 1
      MapPublicIpOnLaunch: true
  GWLBEndpointSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref GWLBEndpointSubnet2CIDR
      AvailabilityZone: !Select
        - 1
        - !Ref AvailabilityZones
      Tags:
        - Key: Name
          Value: GWLB subnet 2
      MapPublicIpOnLaunch: true

  # ------------------------------------------------------------#
  # Create Route table to attach to the GWLB Subnet for GWLB Endpoint
  # ------------------------------------------------------------#
  GWLBEndpointSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: GWLBEndpointSubnet1RouteTable
  GWLBEndpointSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GWLBEndpointSubnet1
      RouteTableId: !Ref GWLBEndpointSubnet1RouteTable

  GWLBEndpointSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: GWLBEndpointSubnet2RouteTable
  GWLBEndpointSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GWLBEndpointSubnet2
      RouteTableId: !Ref GWLBEndpointSubnet2RouteTable

  # ------------------------------------------------------------#
  # Create GWLB Endpoint
  # ------------------------------------------------------------#
  GWLBEndpoint1:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Ref VPCEndpointServiceName
      SubnetIds:
        - !Ref GWLBEndpointSubnet1
      VpcEndpointType: GatewayLoadBalancer
      VpcId: !Ref VPC

  GWLBEndpoint2:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Ref VPCEndpointServiceName
      SubnetIds:
        - !Ref GWLBEndpointSubnet2
      VpcEndpointType: GatewayLoadBalancer
      VpcId: !Ref VPC


  # ------------------------------------------------------------#
  # Create TGW Attachment Subnet for TGW Attachment
  # ------------------------------------------------------------#
  TGWAttachmentSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref TGWAttachmentSubnet1CIDR
      AvailabilityZone: !Select
        - 0
        - !Ref AvailabilityZones
      Tags:
        - Key: Name
          Value: TGW Attachment subnet 1
      MapPublicIpOnLaunch: true
  TGWAttachmentSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref TGWAttachmentSubnet2CIDR
      AvailabilityZone: !Select
        - 1
        - !Ref AvailabilityZones
      Tags:
        - Key: Name
          Value: TGW Attachment subnet 2
      MapPublicIpOnLaunch: true

  # ----------------------------------------------------------------------------#
  # Create Route table to attach to the TGW Attachment Subnet for TGW Attachment
  # ----------------------------------------------------------------------------#
  TGWAttachmentSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: TGWAttachmentSubnet1RouteTable
  TGWAttachmentSubnet1Route:
    DependsOn: GWLBEndpoint1
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref TGWAttachmentSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      VpcEndpointId: !Ref GWLBEndpoint1
  TGWAttachmentSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TGWAttachmentSubnet1
      RouteTableId: !Ref TGWAttachmentSubnet1RouteTable
  TGWAttachmentSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: TGWAttachmentSubnet2RouteTable
  TGWAttachmentSubnet2Route:
    DependsOn: GWLBEndpoint2
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref TGWAttachmentSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      VpcEndpointId: !Ref GWLBEndpoint2
  TGWAttachmentSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TGWAttachmentSubnet2
      RouteTableId: !Ref TGWAttachmentSubnet2RouteTable

  # ------------------------------------------------------------#
  # Create Lambda for modify security vpc route tables
  # ------------------------------------------------------------#
  ModifyRouteTableLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: 
        Fn::Join:
          - ""
          - - Fn::Select:
              - 2
              - Fn::Split:
                - "-"
                - !Ref AWS::StackName
            - "-ModifyRouteTableLambdaRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref ModifyRouteTableLambdaPolicy

  ModifyRouteTableLambdaPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: 
        Fn::Join:
          - ""
          - - Fn::Select:
              - 2
              - Fn::Split:
                - "-"
                - !Ref AWS::StackName
            - "-ModifyRouteTableLambdaPolicy"
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - ec2:ReplaceRoute
            Resource: "*"
            Effect: Allow

  ModifyRouteTableLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json, boto3, logging
          import cfnresponse
          import os
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          destination_cidr_block = "0.0.0.0/0"
          stack_name = os.getenv('StackName')
          route_table_id1 = os.getenv('GWLBESubnetRT1')
          route_table_id2 = os.getenv('GWLBESubnetRT2')
          ec2 = boto3.resource('ec2')
          cf = boto3.client('cloudformation')
          route1 = ec2.Route(route_table_id1,destination_cidr_block)
          route2 = ec2.Route(route_table_id2,destination_cidr_block)

          def lambda_handler(event, context):
            natg1 = cf.describe_stack_resources(stack_name, 'SecurityVPCPublicSubnet1NATGateway')
            natg_id1 = stack_resource[0]['PhysicalResourceId']
            natg2 = cf.describe_stack_resources(stack_name, 'SecurityVPCPublicSubnet2NATGateway')
            natg_id2 = stack_resource[0]['PhysicalResourceId']
            logger.info("event: {}".format(event))
            status = cfnresponse.SUCCESS
            try:
              if event['RequestType'] == 'Create':
                route1.replace(
                    NatGatewayId=natg_id1
                )
                route2.replace(
                    NatGatewayId=natg_id2
                )
            except Exception:
              logger.error('Unhandled exception', exc_info=True)
              status = cfnresponse.FAILED
            finally:
              cfnresponse.send(event, context, status, {}, None)
      Role: !GetAtt ModifyRouteTableLambdaRole.Arn
      Environment: 
        Variables:
          StackName: !Ref AWS::StackName
          GWLBESubnetRT1: !Ref GWLBEndpointSubnet1RouteTable
          GWLBESubnetRT2: !Ref GWLBEndpointSubnet2RouteTable
      FunctionName: 
        Fn::Join:
          - ""
          - - Fn::Select:
              - 2
              - Fn::Split:
                - "-"
                - !Ref AWS::StackName
            - "-ModifyRouteTable-Function"
      Handler: index.lambda_handler
      MemorySize: 128
      Runtime: python3.7
      Timeout: 300

  ModifyRouteTable:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt ModifyRouteTableLambdaFunction.Arn

Outputs:
  GWLBEndpointSubnet1Route:
    Description: ID of GWLB Subnet 1 Route Table
    Value: !Ref GWLBEndpointSubnet1RouteTable
  GWLBEndpointSubnet2Route:
    Description: ID of GWLB Subnet 2 Route Table
    Value: !Ref GWLBEndpointSubnet2RouteTable
  GWLBEndpointSubnet1ID:
    Description: ID of GWLB Subnet 1
    Value: !Ref GWLBEndpointSubnet1
  GWLBEndpointSubnet2ID:
    Description: ID of GWLB Subnet 2
    Value: !Ref GWLBEndpointSubnet2